import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home - ASG Eye Hospital",
  // description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>Home</div>
  )
}