import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact - ASG Eye Hospital",
  // description: "Generated by create next app",
};

export default function Contact() {
  return <div>contact</div>;
}
