import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Hospital - ASG Eye Hospital",
    description: "Generated by create next app",
};

export default function Hospital() {

    return (
        <div>
            component
        </div>
    )
}