import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About - ASG Eye Hospital",
    // description: "Generated by create next app",
};

export default function AboutUs() {

    return (
        <div>
            about us
        </div>
    )
}