import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Service - ASG Eye Hospital",
  // description: "Generated by create next app",
};

export default function Service() {
  return <div>service</div>;
}
